### ISSUE TITLE
Commands not working (TEKNOMW3)

### ISSUE THREAD

**Issue by Rush-er** [diamante0018/ExtensionScript#1]
Hello,
i tried to install your Extension but the commands doesn't work.

I can see the commands added on the list but there is no way to get them working.

1) Downloaded all the 3 files you privided
2) Put all on plugin folder (IW4A)
3) Tried to replace IS from Tekno folder

**Comment by diamante0018** [comment]
Hello, perhaps my instructions inside the README are not clear. Refer to these instructions [LastRelease](https://github.com/diamante0018/ExtensionScript/releases/tag/1.5.0.1).
